### ISSUE TITLE
Looking for key

### ISSUE THREAD

**Issue by mathieucivel** [speculos/speculos-exchanges-poloniex#2]
In default config (no https), with an empty `keys` directory, I have the following error message:

```
Error: ENOENT: no such file or directory, open 'speculos/exchange-poloniex/keys/auth.pub.pem'
    at Error (native)
```

We should have instructions to create needed keys

**Comment by bhamon** [comment]
There is no correlation between the two. This key is required for token creation.
I made the choice to not ship the soft with a default key as it'd be a security issue.

I added the installation steps in the following commit: 6282273a2cd19ad4e3354f90f26460d3de9df5e3. Is that ok?

**Comment by mathieucivel** [comment]
Yep, instructions is what I needed.
